### ISSUE TITLE
NUI Issue

### ISSUE THREAD

**Issue by TlYPN** [cadburry6969/cad-radio#1]
When i have the radio open and the UI of the radio present on my screen, i try and press the numbers 1-9 on my keyboard to set my radio, but my inventory is still picking them up! any chance we can look into it?

**Comment by cadburry6969** [comment]
Have you changed anything after adding the resource?

**Comment by TlYPN** [comment]
no man drag and drop

**Comment by TlYPN** [comment]
still waiting on resolve for this issue.

**Comment by cadburry6969** [comment]
Doesnt seem to be an radio issue so i have closed the issue
